<?php

/**
 * Google Analytics template for Universal Analytics.
 * 
 * PHP Version 5
 * 
 * @category  Template
 * @package   Vbuck_GoogleAnalytics
 * @author    Rick Buczynski <me@rickbuczynski.com>
 * @copyright 2015 Rick Buczynski. All Rights Reserved.
 */

?>
<?php /* @var $this Vbuck_GoogleAnalytics_Block_Ga */ ?>
<!-- Google Analytics -->
<script type='text/javascript'>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    <?php if ($this->getCookieDomain()) : ?>
    ga('create', '<?php echo $this->getAccount(); ?>', { 'cookieDomain': '<?php echo $this->getCookieDomain(); ?>' });
    <?php else : ?>
    ga('create', '<?php echo $this->getAccount(); ?>', 'auto');
    <?php endif; ?>

    <?php if ($this->isAnonymizedIp()) : ?>
    ga('set', 'anonymizeIp', true);
    <?php endif; ?>

    ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
<?php echo $this->getChildHtml('order_tracking'); ?>
<?php echo $this->getChildHtml('custom_tracking'); ?>
<?php // Below does not appear to be used in CE 1.9 ?>
<?php if ($this->getGoogleCheckout()) : ?>
<script src="<?php echo $this->getGoogleCheckoutCodeUrl(); ?>" type="text/javascript"></script>
<?php endif; ?>